<a href="https://colab.research.google.com/github/LissMendoza/inteligennciaArtificial/blob/main/01deJulio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])

a[1] = 888
print(a)



(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [2]:
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
aux=b[1:,1:]
print(aux.shape)
print(aux)

print('antes')
print(b)
print(aux)

aux[1,1]=1000

print('despues')
print(b)
print(aux)

(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
antes
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
despues
[[   1    2    3]
 [  11   22   33]
 [ 111  222 1000]]
[[  22   33]
 [ 222 1000]]


In [3]:
c=np.zeros((4,4))
print(c)
print(c.shape)

d=np.full((4,4),9)
print(d)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [4]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
g=np.random.random((5,5))
print(g)

[[0.42246385 0.11574885 0.47876837 0.97887526 0.55038473]
 [0.29082023 0.59688288 0.10695235 0.79846281 0.01321195]
 [0.56433997 0.582726   0.09402691 0.43276685 0.1863199 ]
 [0.64441938 0.65879246 0.88992711 0.42188546 0.97540799]
 [0.57690944 0.98672953 0.54527367 0.43605805 0.06934376]]


In [6]:
tmp1=np.random.randint(1,20,(4,3))
print(tmp1)
row=np.array([0,1,2,0])
cols=np.arange(4)
print(row)
print(cols)




[[18  9 13]
 [ 3 14  6]
 [19  5 15]
 [19  8 14]]
[0 1 2 0]
[0 1 2 3]


In [16]:
#2 de JULIO

a=np.random.randint(1,10,(3,4))
print(a)
tmp=np.mean(a)
print(tmp)
print(a.mean())

tmp=a.mean(axis=1)
print(tmp)
tmp=a.mean(axis=0)
print(tmp)

aux=a.sum()
print(aux)
medianValue=np.median(a,axis=1)
print(medianValue)

[[2 8 1 5]
 [4 7 1 8]
 [2 7 7 9]]
5.083333333333333
5.083333333333333
[4.   5.   6.25]
[2.66666667 7.33333333 3.         7.33333333]
61
[3.5 5.5 7. ]


In [21]:
#SORTING
#SORTING
b=np.random.randint(1,10,(1,)) # Create a NumPy array of shape (1,)
print(b)
print(b.shape)
b.sort()
print(b)

[3]
(1,)
[3]


In [22]:
c=np.array([2,3,4,2,5,3,5])
print(np.unique(c))

[2 3 4 5]


In [27]:
string1=np.array(['desk','chair','table'])
string2=np.array(['lamp','bulb','chair'])

tmp1=np.intersect1d(string1,string2)
print(tmp1)

tmp2=np.union1d(string1,string2)
print(tmp2)

tmp3=np.setdiff1d(string1,string2)
print(tmp3)

tmp4=np.in1d(string1,string2)
print(tmp4)


['chair']
['bulb' 'chair' 'desk' 'lamp' 'table']
['desk' 'table']
[False  True False]


In [35]:
#broadcasting

aux=np.zeros((4,3))
print(aux)
replicate=np.array([1,2,1])
aux=aux+replicate
print(aux)
replicateCol=np.array([10,10,10])
print(replicateCol.shape)
replicateCol=np.reshape(replicateCol,(3,1))
print(replicateCol.shape)
aux=np.zeros((3,3))
aux1=aux+replicateCol
print(aux1)

print('we are here.....')
vector=np.array((40))
matrixZeros=np.zeros((5,5))
print(matrixZeros)
print(matrixZeros+vector)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
(3,)
(3, 1)
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
we are here.....
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[40. 40. 40. 40. 40.]
 [40. 40. 40. 40. 40.]
 [40. 40. 40. 40. 40.]
 [40. 40. 40. 40. 40.]
 [40. 40. 40. 40. 40.]]
