<a href="https://colab.research.google.com/github/LissMendoza/inteligennciaArtificial/blob/main/01deJulio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])

a[1] = 888
print(a)



(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [21]:
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
aux=b[1:,1:]
print(aux.shape)
print(aux)

print('antes')
print(b)
print(aux)

aux[1,1]=1000

print('despues')
print(b)
print(aux)

(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
antes
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
despues
[[   1    2    3]
 [  11   22   33]
 [ 111  222 1000]]
[[  22   33]
 [ 222 1000]]


In [23]:
c=np.zeros((4,4))
print(c)
print(c.shape)

d=np.full((4,4),9)
print(d)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [25]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
g=np.random.random((5,5))
print(g)

[[0.8399212  0.79493404 0.56141453 0.62643897 0.72091764]
 [0.3890977  0.90602286 0.1380617  0.3783296  0.42752002]
 [0.34428457 0.27646859 0.35257673 0.031761   0.56954206]
 [0.16406292 0.66982563 0.82917782 0.96550663 0.17390922]
 [0.73405021 0.98313681 0.98828615 0.72567673 0.63358056]]


In [33]:
tmp1=np.random.randint(1,20,(4,3))
print(tmp1)
row=np.array([0,1,2,0])
cols=np.arange(4)
print(row)
print(cols)




[[11  2 19]
 [ 3 11 11]
 [ 8 15 18]
 [ 7  6  9]]
[0 1 2 0]
[0 1 2 3]
