<a href="https://colab.research.google.com/github/LissMendoza/inteligennciaArtificial/blob/main/Examen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)

1.25.2


In [2]:
matriz_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(matriz_1d)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
vector = np.random.rand(10)

print("Vector original:")
print(vector)

# Encontrar el índice del valor máximo
indice_maximo = np.argmax(vector)

# Reemplazar el valor máximo por 0
vector[indice_maximo] = 0

print("\nVector con el valor máximo reemplazado por 0:")
print(vector)

Vector original:
[0.4009759  0.20504396 0.12426584 0.67927886 0.54629858 0.64919451
 0.00429726 0.30193952 0.54715574 0.62613855]

Vector con el valor máximo reemplazado por 0:
[0.4009759  0.20504396 0.12426584 0.         0.54629858 0.64919451
 0.00429726 0.30193952 0.54715574 0.62613855]


In [4]:
arr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])
#Se encuentra en la segunda fila (índice 1) y la tercera columna (índice 2)

8


In [5]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [6]:
arr=np.array([1,2,3,4,5,6,7])
ultimos_4_numeros = arr[-4:]

print(ultimos_4_numeros)
#slicing

[4 5 6 7]


In [10]:

g=np.random.random((3,3))
print(g)

[[0.17752008 0.02032018 0.98594337]
 [0.21170934 0.03468283 0.28036236]
 [0.0590002  0.48295574 0.00491879]]



Números impares:
[0.17752008 0.02032018 0.98594337 0.21170934 0.03468283 0.28036236
 0.0590002  0.48295574 0.00491879]


In [12]:
# Crear una matriz 3x3 de números enteros entre 0 y 9
matriz = np.random.randint(0, 10, (3, 3))

print("Matriz original:")
print(matriz)

# Encontrar los números impares
numeros_impares = matriz[matriz % 2 != 0]

print("\nNúmeros impares:")
print(numeros_impares)

Matriz original:
[[9 7 8]
 [2 5 1]
 [7 8 1]]

Números impares:
[9 7 5 1 7 1]


In [15]:
vector = np.arange(10, 49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [16]:

vector = np.array([1, 2, 3, 4, 5])

print("Vector original:")
print(vector)

# Mover el último valor al primer lugar
vector = np.roll(vector, 1)

print("\nVector con el último valor como el primero:")
print(vector)

Vector original:
[1 2 3 4 5]

Vector con el último valor como el primero:
[5 1 2 3 4]


In [30]:
# Crear una matriz 10x10 de números enteros aleatorios entre 0 y 99
matriz = np.random.randint(59, 100, (10, 10))

print("Matriz:")
print(matriz)
print(matriz.max())
print(matriz.min())

Matriz:
[[91 95 85 70 98 79 76 98 74 79]
 [89 83 82 98 91 83 64 87 92 98]
 [62 84 77 68 87 84 73 68 83 88]
 [97 66 59 87 98 75 89 99 82 94]
 [65 80 84 81 70 88 88 87 79 86]
 [64 77 97 79 82 82 91 69 78 94]
 [78 89 85 72 77 70 64 66 77 64]
 [81 67 95 66 79 93 83 81 90 64]
 [89 77 64 85 76 72 65 98 94 68]
 [78 71 83 60 74 99 89 64 92 99]]
99
59


In [21]:
g=np.random.random((3,3,3))
print(g)

[[[0.67139814 0.45989488 0.27695637]
  [0.18049047 0.95295041 0.86590073]
  [0.2000484  0.04196959 0.70127841]]

 [[0.78501309 0.51088383 0.85161388]
  [0.8600371  0.33721974 0.22189352]
  [0.05860136 0.77146918 0.76178559]]

 [[0.10562991 0.15947491 0.17303888]
  [0.58724098 0.30953957 0.76502113]
  [0.42534801 0.71422881 0.48601959]]]
