<a href="https://colab.research.google.com/github/LissMendoza/inteligennciaArtificial/blob/main/Prueba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
# Create a 1D array of numbers from 0 to 9
matriz_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(matriz_1d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0
random_vector = np.random.rand(10)
max_index = random_vector.argmax()
random_vector[max_index] = 0

print(random_vector)


[0.47786902 0.67687515 0.55840534 0.44526789 0.21073531 0.87405559
 0.00378404 0.         0.54909443 0.7384902 ]


In [ ]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])
#Se encuentra en la segunda fila (índice 1) y la tercera columna (índice 2)

8


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr=np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
arr=np.array([1,2,3,4,5,6,7])
ultimos_4_numeros = arr[-4:]

print(ultimos_4_numeros)
#slicing

[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s
# your code here
array_of_trues = np.ones((3, 3), dtype=bool)
array_of_trues = np.full((3, 3), True)
print(array_of_trues)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Extract all odd numbers from arr

# Crear una matriz 3x3 de números enteros entre 0 y 9
matriz = np.random.randint(0, 10, (3, 3))

print("Matriz original:")
print(matriz)

# Encontrar los números impares
numeros_impares = matriz[matriz % 2 != 0]

print("\nNúmeros impares:")
print(numeros_impares)

Matriz original:
[[2 6 7]
 [5 4 2]
 [5 7 2]]

Números impares:
[7 5 5 7]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
# Reverse a vector (first element becomes last)
vector = np.array([1, 2, 3, 4, 5])

print("Vector original:")
print(vector)

# Mover el último valor al primer lugar
vector = np.roll(vector, 1)

print("\nVector con el último valor como el primero:")
print(vector)

Vector original:
[1 2 3 4 5]

Vector con el último valor como el primero:
[5 1 2 3 4]


In [ ]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
matriz = np.random.randint(59, 100, (10, 10))

print("Matriz:")
print(matriz)
print(matriz.max())
print(matriz.min())

Matriz:
[[91 80 77 87 60 94 66 97 63 70]
 [79 85 99 68 92 71 77 60 92 65]
 [93 71 74 64 63 89 91 61 74 77]
 [77 76 64 78 75 94 59 86 97 89]
 [87 63 67 80 83 99 82 87 99 90]
 [63 63 97 79 85 77 73 89 60 86]
 [98 65 81 64 70 89 79 91 82 94]
 [73 81 87 77 84 79 60 79 73 94]
 [98 99 99 91 63 88 68 66 95 89]
 [66 99 76 83 83 67 83 91 65 73]]
99
59


In [ ]:
# Create a 3x3x3 array with random values
array_with_random_values = np.random.rand(3, 3, 3)
print(array_with_random_values)


[[[0.98021604 0.77607025 0.49622349]
  [0.27217428 0.14495604 0.03079633]
  [0.87547117 0.99828054 0.16322704]]

 [[0.15104841 0.47222353 0.72915897]
  [0.07057047 0.29314068 0.98941792]
  [0.86526005 0.53014195 0.60356122]]

 [[0.83063753 0.90526801 0.29182914]
  [0.57986988 0.98908702 0.1045401 ]
  [0.21727829 0.00720892 0.84060246]]]


In [ ]:
# Replace all odd numbers in arr with -1
def reemplazar_impares_bucle(arr):

  for i in range(len(arr)):
    if arr[i] % 2 != 0:
      arr[i] = -1
  return arr

mi_arr = [1, 2, 3, 4, 5]
nueva_arr = reemplazar_impares_bucle(mi_arr)
print(nueva_arr)


[-1, 2, -1, 4, -1]


In [ ]:
# Create an array of type float
array_float = np.array([1, 2.5, 3, 4.1], dtype=float)

array_float = np.empty(4, dtype=float)
array_float[:] = [1, 2.5, 3, 4.1]

print(array_float)


[1.  2.5 3.  4.1]


In [ ]:
# Convert a 1D array to a 2D array with 2 rows
arr = np.array([1, 2, 3, 4, 5, 6])

# Reestructurar el array para que tenga 2 filas
array_2d = arr.reshape(2, -1)  # -1 infiere el número de columnas

print(array_2d)


[[1 2 3]
 [4 5 6]]


In [ ]:
# How to find common values between two arrays?
# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)


# Arrays de ejemplo
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Convertir arrays a conjuntos y encontrar la intersección
valores_comunes = set(Z1) & set(Z2)

# Convertir el conjunto de nuevo a una lista (opcional)
lista_valores_comunes = list(valores_comunes)

print(valores_comunes)
print(lista_valores_comunes)

{0, 8, 4}
[0, 8, 4]


In [ ]:
#  Consider two random array A and B, check if they are equal
# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)

# Arrays aleatorios de ejemplo
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Verificar si los arrays son iguales elemento a elemento usando all()
son_iguales = np.all(A == B)

# Imprimir el resultado
print(f"Los arrays son iguales: {son_iguales}")


Los arrays son iguales: False


In [ ]:
# Stack arrays a and b vertically

# Arrays de ejemplo
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apilar arrays verticalmente usando vstack
array_apilado = np.vstack((a, b))

print(array_apilado)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Stack the arrays a and b horizontally.

# Arrays de ejemplo
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apilar arrays horizontalmente usando hstack
array_apilado = np.hstack((a, b))

print(array_apilado)


[1 2 3 4 5 6]


In [ ]:
# Get all items between 5 and 10 from array tmp.

tmp = np.arange(15)

# Obtener elementos entre 5 y 10 (excluyendo 10) usando slicing
entre_5_y_10 = tmp[5:10]

print(entre_5_y_10)


[5 6 7 8 9]


In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?

def pair_max(x, y):


  # Comprobar si ambas entradas son escalares
  if not np.isscalar(x) and not np.isscalar(y):
    # Si ambas son arrays, asegurarse de que tienen la misma forma
    if not np.array_equal(x.shape, y.shape):
      raise ValueError("Los arrays de entrada deben tener la misma forma.")
    # Aplicar el máximo elemento a elemento utilizando la difusión
    return np.maximum(x, y)
  else:
    # Si al menos una entrada es un escalar, utilizar la función escalar
    return max(x, y)  # Reemplazar maxx con su función max escalar

# Ejemplo de uso con escalares
result1 = pair_max(5, 3)
print(result1)

# Ejemplo de uso con arrays NumPy
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result2 = pair_max(a, b)
print(result2)

5
[6 7 9 8 9 7 5]


In [ ]:
# Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3, 3)
print(arr)

arr[:, [1, 0, 2]] = arr[:, [0, 2, 1]]

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 0 1]
 [5 3 4]
 [8 6 7]]


In [ ]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
random_decimals = np.random.rand(5, 3) * 5 + 5

print(random_decimals)


[[8.68441218 8.75954194 6.80330588]
 [8.27682069 5.90026403 5.57666241]
 [9.01203583 5.16309548 8.4262429 ]
 [7.69543937 8.77401128 9.45768606]
 [9.44015324 5.78527853 8.85433582]]
